// @effect-diagnostics nodeBuiltinImport:off
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

const runners = new Map([
  ["ubuntu-24.04", "ubuntu-24.04"],
  ["blacksmith-2vcpu-ubuntu-2404", "ubuntu-24.04"],
  ["blacksmith-4vcpu-ubuntu-2404", "ubuntu-24.04"],
  ["blacksmith-8vcpu-ubuntu-2404", "ubuntu-24.04"],
  ["blacksmith-6vcpu-macos-26", "macos-26"],
]);

const replaceOnce = ({ text, from, to }: { text: string; from: string; to: string }) => {
  if (text.split(from).length !== 2) {
    throw new Error(`Unsupported upstream CI structure: expected one ${JSON.stringify(from)}`);
  }
  return text.replace(from, () => to);
};

const updateJobField = ({
  body,
  field,
  transform,
}: {
  body: string;
  field: string;
  transform: (value: string) => string;
}) => {
  const pattern = new RegExp(`^    ${field}: (.*)$`, "gm");
  if ([...body.matchAll(pattern)].length !== 1) {
    throw new Error(`Unsupported upstream CI job: expected one plain ${field}`);
  }
  return body.replace(
    pattern,
    (_line: string, value: string) => `    ${field}: ${transform(value)}`,
  );
};

const generateCI = (source: string) => {
  let workflow = replaceOnce({ text: source, from: "name: CI\n", to: "name: Workbench CI\n" });
  workflow = replaceOnce({ text: workflow, from: "  group: ci-", to: "  group: workbench-ci-" });
  const sections = workflow.split("\njobs:\n");
  if (sections.length !== 2) throw new Error("Unsupported upstream CI: expected one jobs mapping");
  const [header, jobs] = sections;
  if (header === undefined || jobs === undefined) throw new Error("Upstream CI jobs are missing");
  let jobCount = 0;
  let lintFound = false;
  let testFound = false;
  // Preserve upstream YAML verbatim outside these job fields and the fork validation step.
  const generatedJobs = jobs.replace(
    /^  ([\w-]+):\n([\s\S]*?)(?=^  [\w-]+:\n|(?![\s\S]))/gm,
    (_job: string, id: string, originalBody: string) => {
      jobCount++;
      let body = updateJobField({
        body: originalBody,
        field: "runs-on",
        transform: (runner) => {
          const replacement = runners.get(runner);
          if (!replacement) throw new Error(`Unsupported upstream CI runner: ${runner}`);
          return replacement;
        },
      });
      // The artifact consumer uses the platform default timeout upstream.
      if (id !== "transfer-report" || /^    timeout-minutes:/m.test(body))
        body = updateJobField({
          body,
          field: "timeout-minutes",
          transform: (timeout) => {
            if (timeout !== "5" && timeout !== "10") {
              throw new Error(`Unsupported upstream CI job timeout: ${timeout}`);
            }
            return timeout === "10" ? "30" : timeout;
          },
        });
      body = updateJobField({
        body,
        field: "name",
        transform: (name) => {
          if (!name || /^["'|>&*!{[]/.test(name)) {
            throw new Error(`Unsupported upstream CI job name: ${name}`);
          }
          return `Workbench ${name}`;
        },
      });
      if (id === "lint") {
        lintFound = true;
        body = replaceOnce({
          text: body,
          from: "      - name: Check unused code\n",
          to: "      - name: Verify fork CI\n        run: |\n          node scripts/workbench-ci.ts --check\n          vp test run scripts/workbench-ci.test.ts\n\n      - name: Check unused code\n",
        });
      }
      if (id === "test") {
        testFound = true;
        body = replaceOnce({
          text: body,
          from: "run: vp run --parallel --concurrency-limit 4 ",
          to: "run: vp run --parallel --concurrency-limit 1 ",
        });
      }
      return `  ${id}:\n${body}`;
    },
  );
  const jobHeaders = jobs.split("\n").filter((line) => /^  [^\s#]/.test(line));
  if (jobHeaders.length !== jobCount) throw new Error("Unsupported upstream CI job mapping");
  if (jobCount === 0 || !lintFound || !testFound) {
    throw new Error("Unsupported upstream CI: lint and package test jobs are required");
  }
  return (
    "# Generated by node scripts/workbench-ci.ts; edit the generator, not this file.\n" +
    "# Upstream jobs are retained; fork check names have a Workbench prefix.\n" +
    `${header}\njobs:\n${generatedJobs}`
  );
};

const generateReport = (source: string) => {
  const sections = source.split("\njobs:\n");
  const jobs = sections[1];
  const jobHeaders = jobs?.split("\n").filter((line) => /^  [^\s#]/.test(line));
  const reportRunners = [...(jobs ?? "").matchAll(/^    runs-on: (.*)$/gm)];
  if (
    sections.length !== 2 ||
    jobHeaders?.length !== 1 ||
    jobHeaders[0] !== "  publish:" ||
    reportRunners.length !== 1 ||
    reportRunners[0]?.[1] !== "ubuntu-24.04"
  ) {
    throw new Error("Unsupported upstream thread transfer report infrastructure");
  }
  let workflow = replaceOnce({
    text: source,
    from: "name: Thread Transfer Report\n",
    to: "name: Workbench Thread Transfer Report\n",
  });
  workflow = replaceOnce({
    text: workflow,
    from: "    workflows: [CI]\n",
    to: "    workflows: [Workbench CI]\n",
  });
  workflow = replaceOnce({
    text: workflow,
    from: "      group: thread-transfer-report-",
    to: "      group: workbench-thread-transfer-report-",
  });
  return (
    "# Generated by node scripts/workbench-ci.ts; edit the generator, not this file.\n" + workflow
  );
};

try {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    throw new Error("Usage: node scripts/workbench-ci.ts [--check]");
  }
  const workflows = [
    { source: "ci", generate: generateCI },
    { source: "thread-transfer-report", generate: generateReport },
  ].map(({ source, generate }) => ({
    outputPath: NodePath.resolve(`.github/workflows/workbench-${source}.yml`),
    generated: generate(
      NodeFS.readFileSync(NodePath.resolve(`.github/workflows/${source}.yml`), "utf8"),
    ),
  }));
  for (const { outputPath, generated } of workflows) {
    if (args[0] === "--check") {
      if (!NodeFS.existsSync(outputPath) || NodeFS.readFileSync(outputPath, "utf8") !== generated) {
        throw new Error("Fork CI is stale; run node scripts/workbench-ci.ts");
      }
    } else {
      NodeFS.writeFileSync(outputPath, generated);
    }
  }
} catch (error) {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
}
